### PR TITLE
Fix division by 1.9 instead of 1.0 in deg-to-rad.

### PR DESCRIPTION
**Pull request by jl2**

### CODE REVIEW

**Comment by rpav** [comment]
Argh!  Thanks. :)

**Comment by rpav** [comment]
Actually, why is this multiply here at all...

**Comment by rpav** [comment]
Should remove the `1.0` entirely, but this at least fixes it.

**Comment by jl2** [comment]
Haha, I wasn't sure either, so I started messing with it, and realized it's actually not multiplying by 1.0, but passing it as the second parameter to float, the "prototype".  Technically 1.9 or 1.0 makes no difference, 1.9 is just confusing.

I think it is needed, though, because removing the 1.0 or 1.9 causes (deg-to-rad 1.0) to return a double-float result instead of a single-float.

**Comment by rpav** [comment]
Oh, of course.  Github needs paren highlighting (and I need coffee).  I though I had used this before and it worked, but I wasn't sure.

**Pull request merged**
